[2024-12-23T20:00:43.496+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T20:00:43.512+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_connect.my_task scheduled__2024-12-22T08:00:00+00:00 [queued]>
[2024-12-23T20:00:43.518+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_connect.my_task scheduled__2024-12-22T08:00:00+00:00 [queued]>
[2024-12-23T20:00:43.518+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-23T20:00:43.529+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): my_task> on 2024-12-22 08:00:00+00:00
[2024-12-23T20:00:43.534+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1868) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T20:00:43.534+0000] {standard_task_runner.py:63} INFO - Started process 1869 to run task
[2024-12-23T20:00:43.535+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_connect', 'my_task', 'scheduled__2024-12-22T08:00:00+00:00', '--job-id', '1056', '--raw', '--subdir', 'DAGS_FOLDER/dag_connect.py', '--cfg-path', '/tmp/tmp_ahaqh0x']
[2024-12-23T20:00:43.536+0000] {standard_task_runner.py:91} INFO - Job 1056: Subtask my_task
[2024-12-23T20:00:43.567+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_connect.my_task scheduled__2024-12-22T08:00:00+00:00 [running]> on host 87a1e11545b0
[2024-12-23T20:00:43.633+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_connect' AIRFLOW_CTX_TASK_ID='my_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-22T08:00:00+00:00'
[2024-12-23T20:00:43.634+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T20:00:43.650+0000] {base.py:84} INFO - Using connection ID 'my_postgres' for task execution.
[2024-12-23T20:00:43.650+0000] {logging_mixin.py:188} INFO - Host: jdbc:postgresql://localhost:5436/de_course_db
[2024-12-23T20:00:43.650+0000] {logging_mixin.py:188} INFO - Login: postgres
[2024-12-23T20:00:43.650+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-23T20:00:43.651+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T20:00:43.659+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_connect, task_id=my_task, run_id=scheduled__2024-12-22T08:00:00+00:00, execution_date=20241222T080000, start_date=20241223T200043, end_date=20241223T200043
[2024-12-23T20:00:43.707+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-23T20:00:43.720+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T20:00:43.721+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
