[2024-12-23T19:41:02.870+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T19:41:02.896+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_var.bash_ex2 manual__2024-12-23T19:41:02.083985+00:00 [queued]>
[2024-12-23T19:41:02.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_var.bash_ex2 manual__2024-12-23T19:41:02.083985+00:00 [queued]>
[2024-12-23T19:41:02.907+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-23T19:41:02.923+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): bash_ex2> on 2024-12-23 19:41:02.083985+00:00
[2024-12-23T19:41:02.930+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1592) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T19:41:02.931+0000] {standard_task_runner.py:63} INFO - Started process 1593 to run task
[2024-12-23T19:41:02.933+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_var', 'bash_ex2', 'manual__2024-12-23T19:41:02.083985+00:00', '--job-id', '1048', '--raw', '--subdir', 'DAGS_FOLDER/dag_var.py', '--cfg-path', '/tmp/tmpmxhsy0ch']
[2024-12-23T19:41:02.934+0000] {standard_task_runner.py:91} INFO - Job 1048: Subtask bash_ex2
[2024-12-23T19:41:02.971+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_var.bash_ex2 manual__2024-12-23T19:41:02.083985+00:00 [running]> on host 87a1e11545b0
[2024-12-23T19:41:03.038+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_var' AIRFLOW_CTX_TASK_ID='bash_ex2' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T19:41:02.083985+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T19:41:02.083985+00:00'
[2024-12-23T19:41:03.039+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T19:41:03.049+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-23T19:41:03.049+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Task 2 now $(date)"']
[2024-12-23T19:41:03.058+0000] {subprocess.py:86} INFO - Output:
[2024-12-23T19:41:03.060+0000] {subprocess.py:93} INFO - Task 2 now Mon Dec 23 19:41:03 UTC 2024
[2024-12-23T19:41:03.061+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-23T19:41:03.061+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T19:41:03.080+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_var, task_id=bash_ex2, run_id=manual__2024-12-23T19:41:02.083985+00:00, execution_date=20241223T194102, start_date=20241223T194102, end_date=20241223T194103
[2024-12-23T19:41:03.106+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-23T19:41:03.125+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-23T19:41:03.126+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
