[2024-12-23T19:41:29.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T19:41:29.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_var.bash_ex2 manual__2024-12-23T19:36:46.368469+00:00 [queued]>
[2024-12-23T19:41:29.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_var.bash_ex2 manual__2024-12-23T19:36:46.368469+00:00 [queued]>
[2024-12-23T19:41:29.676+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-23T19:41:29.686+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): bash_ex2> on 2024-12-23 19:36:46.368469+00:00
[2024-12-23T19:41:29.692+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1598) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T19:41:29.692+0000] {standard_task_runner.py:63} INFO - Started process 1599 to run task
[2024-12-23T19:41:29.693+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_var', 'bash_ex2', 'manual__2024-12-23T19:36:46.368469+00:00', '--job-id', '1050', '--raw', '--subdir', 'DAGS_FOLDER/dag_var.py', '--cfg-path', '/tmp/tmpsox69to0']
[2024-12-23T19:41:29.693+0000] {standard_task_runner.py:91} INFO - Job 1050: Subtask bash_ex2
[2024-12-23T19:41:29.725+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_var.bash_ex2 manual__2024-12-23T19:36:46.368469+00:00 [running]> on host 87a1e11545b0
[2024-12-23T19:41:29.788+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_var' AIRFLOW_CTX_TASK_ID='bash_ex2' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T19:36:46.368469+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T19:36:46.368469+00:00'
[2024-12-23T19:41:29.789+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T19:41:29.799+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-23T19:41:29.799+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Task 2 now $(date)"']
[2024-12-23T19:41:29.807+0000] {subprocess.py:86} INFO - Output:
[2024-12-23T19:41:29.810+0000] {subprocess.py:93} INFO - Task 2 now Mon Dec 23 19:41:29 UTC 2024
[2024-12-23T19:41:29.811+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-23T19:41:29.811+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T19:41:29.829+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_var, task_id=bash_ex2, run_id=manual__2024-12-23T19:36:46.368469+00:00, execution_date=20241223T193646, start_date=20241223T194129, end_date=20241223T194129
[2024-12-23T19:41:29.865+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-23T19:41:29.883+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-23T19:41:29.884+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
